--  @cre_all.sql
--
spoo cre_all
prompt drop_all_tables ...
@drop_all_tables
prompt cre_all_tables ...
@cre_all_tables
prompt ins_all_tables ...
@ins_all_tables
prompt cre_auto_bu ...
@cre_auto_bu
prompt ins_new_company ...
@ins_new_company
prompt Done ...
spoo off
quit

