-- @cre_address_master
--
create sequence seq_address_master;
create table address_master (
-- am_address_id      integer      GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
am_address_id      number      DEFAULT seq_address_master.NEXTVAL,
am_address1        varchar2(50),
am_address2        varchar2(50),
am_city            varchar2(50),
am_state_prov      varchar2(50),
am_country         varchar2(50),
am_postal_code     varchar2(10),
am_email           varchar2(40),
am_home_phone      varchar2(15),
am_cell_phone      varchar2(15),
am_fax             varchar2(15),
constraint pk_address_master primary key (am_address_id)
);
